# Generated by Django 4.2.28 on 2026-02-10 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0002_connector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ration', models.PositiveIntegerField()),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='network.connector')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='network.network')),
            ],
        ),
    ]
