# Generated by Django 4.2.28 on 2026-02-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routing',
            old_name='ration',
            new_name='ratio',
        ),
    ]
