# Generated by Django 4.2.28 on 2026-02-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('routing', '0002_rename_ration_routing_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='routing',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
            preserve_default=False,
        ),
    ]
