# Generated by Django 4.2.28 on 2026-02-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_routing_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='routing',
            name='conf_added',
            field=models.BooleanField(default=False),
        ),
    ]
